# Docker Compose configuration for the morphic-stack development environment

name: morphic-stack
services:
  morphic:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/morphic}:latest
    command: bun start -H 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - morphic:builder
        - morphic:latest
    env_file: .env.local # Load environment variables
    ports:
      - '3000:3000' # Maps port 3000 on the host to port 3000 in the container.
    depends_on:
      - redis
      - searxng
      - qdrant

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng
    ports:
      - '${SEARXNG_PORT:-8080}:8080'
    env_file: .env.local # can remove if you want to use env variables or in settings.yml
    volumes:
      - ./searxng-limiter.toml:/etc/searxng/limiter.toml
      - ./searxng-settings.yml:/etc/searxng/settings.yml
      - searxng_data:/data

  # Note: unstructured.io image is not available for ARM64 (Apple Silicon)
  # You can enable this service on x86_64 platforms by uncommenting:
  #
  # unstructured:
  #   image: quay.io/unstructured-io/unstructured-api:latest
  #   ports:
  #     - '8000:8000'
  #   command: --port 8000 --host 0.0.0.0

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/amd64  # Explicit platform to ensure compatibility
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=*

volumes:
  redis_data:
  searxng_data:
  qdrant_data:
